CALL registerPlayer('bob99','pass','robert','young');
CALL registerPlayer('charles99','pass','charles','hardy');
CALL registerStoreOwner('billyman123','pass','buffalo','bill');
CALL addUserCard('bob99','Blue-Eyes Alternative Ultimate Dragon','Yu-Gi-Oh!','good');
CALL addUserCard('bob99','Blue-Eyes Alternative Ultimate Dragon','Yu-Gi-Oh!','good');
CALL addUserCard('bob99','Meklord Army of Skiel','Yu-Gi-Oh!','good');
CALL addUserCard('bob99','Meklord Army of Skiel','Yu-Gi-Oh!','good');
CALL addUserCard('bob99','Meklord Army of Skiel','Yu-Gi-Oh!','bad');
CALL addUserCard('billyman123','Blue-Eyes Alternative Ultimate Dragon','Yu-Gi-Oh!','good');
CALL removeUserCard('bob99','Meklord Army of Skiel','bad');
CALL removeUserCard('bob99','Meklord Army of Skiel','good');
CALL createOffer('charles99', 'bob99');
CALL addUserCard('charles99','Absolute Crusader','Yu-Gi-Oh!','good');
CALL addToOffer(1,5,'requestor');
CALL addToOffer(1,2,'decider');
CALL createStore('bob99','robert`s emporium of cards');
CALL setFeatured('robert`s emporium of cards',1);
CALL unSetFeatured('robert`s emporium of cards');
--SELECT * FROM getUserCards('bob99');